### ISSUE TITLE
scanTableForLongTexts also checks longtext

### ISSUE THREAD

**Issue by stefanhipfel** [SUSE/psql2mysql#48]
Hi,

the check for long texts uses `MAX_TEXT_LEN = 65536`, which is true for normal TEXT in mariadb. But not for medium or longtext(4gb), e.g. in the case of `ironic nodes.instance_info` (longtext). Here we have a false positive precheck.
Here the precheck should also take the mariadb column type into consideration.

Thanks

**Comment by jsuchome** [comment]
Thanks Stefan, that's a good point. 

I just curious - do you plan to use the tool soon so it would really be a problem if it is not fixed?

(My current feeling is that the tool itself is addressing quite old system setups and I would be surprised someone might still need to use it in 2020)

**Comment by stefanhipfel** [comment]
Hi,

thanks for the quick reply. I am using the tool atm! If I find the time, I could provide a pr.
I think for openstack this tool is still relevant, as openstack is moving away from postgres to mariadb.

**Comment by jsuchome** [comment]
See the linked PR....

**Comment by jsuchome** [comment]
@stefanhipfel , does the proposed patch work correctly in your case?

**Comment by stefanhipfel** [comment]
yes thank you very much!
